site_name: E志者协会维修手册
site_url: https://docs.zjueva.net
repo_url: https://github.com/ZJUEVA/EVA-manual
nav:
  - 首页: 
    - 首页: index.md
    - E志维修相关: process.md
    - 校外价格表: costs.md
  - 电脑硬件: 
    - 概述: hardware/index.md
    - 开始拆卸: hardware/start-disassembling/index.md
    - 清灰换硅脂: hardware/clean-dust/index.md
    - 厂家下载链接合集: hardware/driver-links.md
    - BIOS 设置: hardware/BIOS-settings.md
    - 数据恢复: hardware/data-recovery.md
    - 电池: hardware/battery.md
    - 维修案例:
      - hardware/case/1.md
      - hardware/case/2.md
      - hardware/case/3.md
      - hardware/case/4.md
  - 电脑软件: 
    - 概述: software/index.md
    - 重装系统: software/reinstall-system.md
    - Bitlocker: software/bitlocker.md
    - 备份数据: software/backup-data.md
    - 制作启动盘: software/make-startup-device.md
    - 移动C盘文件夹: software/move-folders-from-disk-C/index.md
    - 维修案例:
      - software/case/1.md
  - 电器维修: 
    - appliance/index.md
  - 2025 购机指南:
    - 购机指南（上）: purchasing-guide/2025-1/index.md

theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer
    - content.code.copy
copyright: "<p>© 2025<a href='https://zjueva.net'> E志者协会</a></p><p>除特殊注明外，本作品采用<a href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans>CC BY-NC-SA 4.0</a>许可。作品中引用他人的内容，权利归属原作者所有。</p>"

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
